/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;



/**
 *
 * @author roca
 */
public class JFCaperucita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFCaperucita.class.getName());

    /**
     * Creates new form JFCaperucita
     */
    public JFCaperucita() {
    initComponents();  
    }
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        fondo = new javax.swing.JLabel();
        btnizquierda = new javax.swing.JButton();
        btnCanasta = new javax.swing.JButton();
        btnArriba = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        lblCaperucita = new javax.swing.JLabel();
        lblLobo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caperucita Roja Layout.png"))); // NOI18N
        jLayeredPane1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnizquierda.setBackground(new java.awt.Color(179, 117, 126));
        btnizquierda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnizquierda.setForeground(new java.awt.Color(255, 255, 255));
        btnizquierda.setText("←");
        btnizquierda.setToolTipText("");
        btnizquierda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnizquierda.setInheritsPopupMenu(true);
        jLayeredPane1.setLayer(btnizquierda, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnizquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 70, 50));

        btnCanasta.setBackground(new java.awt.Color(179, 117, 126));
        btnCanasta.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnCanasta.setForeground(new java.awt.Color(255, 255, 255));
        btnCanasta.setText("Canasta");
        btnCanasta.setToolTipText("");
        btnCanasta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCanasta.setInheritsPopupMenu(true);
        jLayeredPane1.setLayer(btnCanasta, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnCanasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 150, 50));

        btnArriba.setBackground(new java.awt.Color(179, 117, 126));
        btnArriba.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnArriba.setForeground(new java.awt.Color(255, 255, 255));
        btnArriba.setText("↑");
        btnArriba.setToolTipText("");
        btnArriba.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArriba.setInheritsPopupMenu(true);
        jLayeredPane1.setLayer(btnArriba, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 70, 50));

        btnDerecha.setBackground(new java.awt.Color(179, 117, 126));
        btnDerecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDerecha.setForeground(new java.awt.Color(255, 255, 255));
        btnDerecha.setText("→");
        btnDerecha.setToolTipText("");
        btnDerecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDerecha.setInheritsPopupMenu(true);
        btnDerecha.addActionListener(this::btnDerechaActionPerformed);
        jLayeredPane1.setLayer(btnDerecha, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 70, 50));

        btnAbajo.setBackground(new java.awt.Color(179, 117, 126));
        btnAbajo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAbajo.setForeground(new java.awt.Color(255, 255, 255));
        btnAbajo.setText("↓");
        btnAbajo.setToolTipText("");
        btnAbajo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbajo.setInheritsPopupMenu(true);
        btnAbajo.addActionListener(this::btnAbajoActionPerformed);
        jLayeredPane1.setLayer(btnAbajo, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(btnAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 70, 50));

        lblCaperucita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caperucita.png"))); // NOI18N
        lblCaperucita.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLayeredPane1.setLayer(lblCaperucita, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(lblCaperucita, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 456, -1, -1));

        lblLobo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lobo.png"))); // NOI18N
        lblLobo.setPreferredSize(new java.awt.Dimension(64, 100));
        jLayeredPane1.setLayer(lblLobo, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(lblLobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your ghj code here:
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFCaperucita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbajo;
    public javax.swing.JButton btnArriba;
    public javax.swing.JButton btnCanasta;
    public javax.swing.JButton btnDerecha;
    public javax.swing.JButton btnizquierda;
    private javax.swing.JLabel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JLabel lblCaperucita;
    public javax.swing.JLabel lblLobo;
    // End of variables declaration//GEN-END:variables
}
