/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ACEVEDO
 */
public class JFInterfaz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFInterfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public JFInterfaz() {
        initComponents();
        Panel1.setLayout(null);
        ImageIcon iconoCasa = new ImageIcon(getClass().getResource("/imagen/Casa.png"));
        ImageIcon iconoLobo = new ImageIcon(getClass().getResource("/imagen/Lobo.png"));
        ImageIcon iconoAbuelita = new ImageIcon(getClass().getResource("/imagen/Abuelita.png"));
        ImageIcon iconoCaperucita = new ImageIcon(getClass().getResource("/imagen/Caperucita.png"));
        ImageIcon iconoLeñador = new ImageIcon(getClass().getResource("/imagen/Leñador.png"));

        Image imagenCasa = iconoCasa.getImage();
        Image imagenLobo = iconoLobo.getImage();
        Image imagenCaperucita = iconoCaperucita.getImage();
        Image imagen = iconoAbuelita.getImage();
        Image imagenLeñador = iconoLeñador.getImage();
        
        Image ajustarCasa = imagenCasa.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        Image ajustarLeñador = imagenLeñador.getScaledInstance(Label5Leñador.getWidth(), Label5Leñador.getHeight(), Image.SCALE_SMOOTH);
        Image ajustarLobo = imagenLobo.getScaledInstance(Label4Lobo.getWidth(), Label4Lobo.getHeight(), Image.SCALE_SMOOTH);
        Image ajustada = imagen.getScaledInstance(jLabel2Abuelita.getWidth(), jLabel2Abuelita.getHeight(), Image.SCALE_SMOOTH);
        Image ajustadaCaperucita = imagenCaperucita.getScaledInstance(jLabel3Caper.getWidth(), jLabel3Caper.getHeight(), Image.SCALE_SMOOTH);
        
        jLabel1.setIcon(new ImageIcon(ajustarCasa) );
        jLabel3Caper.setIcon(new ImageIcon(ajustadaCaperucita));
        jLabel2Abuelita.setIcon(new ImageIcon(ajustada));
        Label4Lobo.setIcon(new ImageIcon(ajustarLobo));
        Label5Leñador.setIcon(new ImageIcon(ajustarLeñador));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2Abuelita = new javax.swing.JLabel();
        jLabel3Caper = new javax.swing.JLabel();
        Label4Lobo = new javax.swing.JLabel();
        Label5Leñador = new javax.swing.JLabel();
        btnEvento = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ComboCaperucita = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ComboAbuela = new javax.swing.JComboBox<>();
        ComboLeñador = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboLobo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnMostrarInformacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(0, 102, 102));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(109, 110));
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 98, -1));

        jLabel2Abuelita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Abuelita.png"))); // NOI18N
        Panel1.add(jLabel2Abuelita, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 35, 87, 93));

        jLabel3Caper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Caperucita.png"))); // NOI18N
        Panel1.add(jLabel3Caper, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 420, 87, 92));

        Label4Lobo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Lobo.png"))); // NOI18N
        Panel1.add(Label4Lobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 418, 87, 94));

        Label5Leñador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Leñador.png"))); // NOI18N
        Panel1.add(Label5Leñador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 87, 89));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 550, 530));

        btnEvento.setText("Siguiente");
        getContentPane().add(btnEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 200, 30));

        btnReiniciar.setText("Reiniciar");
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 200, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextArea1.setColumns(20);
        TextArea1.setLineWrap(true);
        TextArea1.setRows(5);
        TextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, 430, 320));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 350));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboCaperucita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantar", "Bailar", "Mirar Facebook" }));
        jPanel2.add(ComboCaperucita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Abuela:");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        ComboAbuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gritar", "Estudiar POO", "Cambiarse ropa" }));
        jPanel2.add(ComboAbuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));

        ComboLeñador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salvar", "Regalar dulce", "Rellenar Panza", "Abrir Panza" }));
        jPanel2.add(ComboLeñador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Leñador:");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        ComboLobo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correr", "Tragar Caperucita", "Disfrazarse", "Tragar Abuelita" }));
        jPanel2.add(ComboLobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Caperucita:");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lobo:");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, 140));

        btnMostrarInformacion.setText("Información");
        getContentPane().add(btnMostrarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFInterfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboAbuela;
    public javax.swing.JComboBox<String> ComboCaperucita;
    public javax.swing.JComboBox<String> ComboLeñador;
    public javax.swing.JComboBox<String> ComboLobo;
    public javax.swing.JLabel Label4Lobo;
    public javax.swing.JLabel Label5Leñador;
    public javax.swing.JPanel Panel1;
    public javax.swing.JTextArea TextArea1;
    public javax.swing.JButton btnEvento;
    public javax.swing.JButton btnMostrarInformacion;
    public javax.swing.JButton btnReiniciar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2Abuelita;
    public javax.swing.JLabel jLabel3Caper;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        public FondoPanel() {
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics e) {
            super.paintComponent(e);
            if (imagen == null) {
                imagen = new ImageIcon(
                        getClass().getResource("/imagen/Bosque.png")
                ).getImage();
            }
            e.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }

}
