/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Asignatura;
import modelo.Departamento;

/**
 *
 * @author roca
 */
public class JFIngresarEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFIngresarEmpleado.class.getName());

    /**
     * Creates new form IngresarEmpleado
     */
    public JFIngresarEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateIngreso = new com.toedter.calendar.JDateChooser();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comBTipoEmpleado = new javax.swing.JComboBox<>();
        jPanelProfesor = new javax.swing.JLayeredPane();
        lblEspecialidad = new javax.swing.JLabel();
        lblTipoProfesor = new javax.swing.JLabel();
        comBTipoProfesor = new javax.swing.JComboBox<>();
        jPanelAsignatura = new javax.swing.JLayeredPane();
        lblAsignatura = new javax.swing.JLabel();
        lblTextoProfesor = new javax.swing.JLabel();
        comBAsignatura = new javax.swing.JComboBox<>();
        btnAñadirAsignatura = new javax.swing.JButton();
        txtEspecialidad = new javax.swing.JTextField();
        jPanelAdministrativo = new javax.swing.JLayeredPane();
        jPanelDepartamento = new javax.swing.JLayeredPane();
        lblIdDepartamento = new javax.swing.JLabel();
        txtIdAdministrativo = new javax.swing.JTextField();
        lblNombreDepartamento = new javax.swing.JLabel();
        txtNombreDepartamento = new javax.swing.JTextField();
        lblEnfoque = new javax.swing.JLabel();
        txtEnfoque = new javax.swing.JTextField();
        btnGuardarDepartamento = new javax.swing.JButton();
        lblTextoDepartamento = new javax.swing.JLabel();
        comBDepartamento = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Basicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("id:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombres:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellidos:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fechas de Ingreso:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cargo:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Salario Base:");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalario)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDateIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, 140));

        jLabel8.setText("¿Qué tipo de empleado es?");
        jLayeredPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, 20));

        comBTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Profesor", "Administrativo" }));
        jLayeredPane2.add(comBTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 150, -1));

        jPanelProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos específicos: Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        jPanelProfesor.setToolTipText("");
        jPanelProfesor.setAutoscrolls(true);
        jPanelProfesor.setEnabled(false);

        lblEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspecialidad.setText("Especialidad:");
        lblEspecialidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblEspecialidad.setEnabled(false);

        lblTipoProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoProfesor.setText("Tipo Profesor:");
        lblTipoProfesor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTipoProfesor.setEnabled(false);

        comBTipoProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catedratico", "Ocasional", "Asociado" }));
        comBTipoProfesor.setToolTipText("");
        comBTipoProfesor.setAutoscrolls(true);
        comBTipoProfesor.setEnabled(false);

        jPanelAsignatura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Asignaturas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 10))); // NOI18N
        jPanelAsignatura.setEnabled(false);

        lblAsignatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsignatura.setText("Asignaturas:");
        lblAsignatura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAsignatura.setEnabled(false);

        lblTextoProfesor.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTextoProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoProfesor.setText("<html> (Puede añadir varias asignaturas a un profesor) </html>");
        lblTextoProfesor.setEnabled(false);

        comBAsignatura.setToolTipText("");
        comBAsignatura.setAutoscrolls(true);
        comBAsignatura.setEnabled(false);

        btnAñadirAsignatura.setText("Añadir");
        btnAñadirAsignatura.setToolTipText("");
        btnAñadirAsignatura.setAutoscrolls(true);
        btnAñadirAsignatura.setEnabled(false);
        btnAñadirAsignatura.addActionListener(this::btnAñadirAsignaturaActionPerformed);

        jPanelAsignatura.setLayer(lblAsignatura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelAsignatura.setLayer(lblTextoProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelAsignatura.setLayer(comBAsignatura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelAsignatura.setLayer(btnAñadirAsignatura, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelAsignaturaLayout = new javax.swing.GroupLayout(jPanelAsignatura);
        jPanelAsignatura.setLayout(jPanelAsignaturaLayout);
        jPanelAsignaturaLayout.setHorizontalGroup(
            jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsignaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsignaturaLayout.createSequentialGroup()
                        .addComponent(lblAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTextoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsignaturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAñadirAsignatura)
                .addGap(91, 91, 91))
        );
        jPanelAsignaturaLayout.setVerticalGroup(
            jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsignaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignatura)
                    .addComponent(comBAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAñadirAsignatura)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        txtEspecialidad.setToolTipText("");
        txtEspecialidad.setEnabled(false);

        jPanelProfesor.setLayer(lblEspecialidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelProfesor.setLayer(lblTipoProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelProfesor.setLayer(comBTipoProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelProfesor.setLayer(jPanelAsignatura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelProfesor.setLayer(txtEspecialidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelProfesorLayout = new javax.swing.GroupLayout(jPanelProfesor);
        jPanelProfesor.setLayout(jPanelProfesorLayout);
        jPanelProfesorLayout.setHorizontalGroup(
            jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelAsignatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProfesorLayout.createSequentialGroup()
                            .addComponent(lblTipoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comBTipoProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProfesorLayout.createSequentialGroup()
                            .addComponent(lblEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelProfesorLayout.setVerticalGroup(
            jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfesorLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidad)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoProfesor)
                    .addComponent(comBTipoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jPanelAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLayeredPane2.add(jPanelProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 300, 250));

        jPanelAdministrativo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos específicos: Administrativo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        jPanelAdministrativo.setAutoscrolls(true);
        jPanelAdministrativo.setEnabled(false);

        jPanelDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Departamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 10))); // NOI18N
        jPanelDepartamento.setEnabled(false);

        lblIdDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdDepartamento.setText("id:");
        lblIdDepartamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblIdDepartamento.setEnabled(false);

        txtIdAdministrativo.setEnabled(false);

        lblNombreDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreDepartamento.setText("Nombre:");
        lblNombreDepartamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreDepartamento.setEnabled(false);

        txtNombreDepartamento.setEnabled(false);

        lblEnfoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnfoque.setText("Enfoque:");
        lblEnfoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblEnfoque.setEnabled(false);

        txtEnfoque.setEnabled(false);

        btnGuardarDepartamento.setText("Guardar");
        btnGuardarDepartamento.setAutoscrolls(true);
        btnGuardarDepartamento.setEnabled(false);

        jPanelDepartamento.setLayer(lblIdDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDepartamento.setLayer(txtIdAdministrativo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDepartamento.setLayer(lblNombreDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDepartamento.setLayer(txtNombreDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDepartamento.setLayer(lblEnfoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDepartamento.setLayer(txtEnfoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelDepartamento.setLayer(btnGuardarDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelDepartamentoLayout = new javax.swing.GroupLayout(jPanelDepartamento);
        jPanelDepartamento.setLayout(jPanelDepartamentoLayout);
        jPanelDepartamentoLayout.setHorizontalGroup(
            jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIdDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(lblEnfoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDepartamentoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardarDepartamento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDepartamentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDepartamentoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtEnfoque, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdAdministrativo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanelDepartamentoLayout.setVerticalGroup(
            jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdDepartamento)
                    .addComponent(txtIdAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDepartamento)
                    .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnfoque)
                    .addComponent(txtEnfoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnGuardarDepartamento)
                .addContainerGap())
        );

        lblTextoDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoDepartamento.setText("Escoja el departamento que pertenecerá:");
        lblTextoDepartamento.setEnabled(false);

        comBDepartamento.setAutoscrolls(true);
        comBDepartamento.setEnabled(false);
        comBDepartamento.addActionListener(this::comBDepartamentoActionPerformed);

        jPanelAdministrativo.setLayer(jPanelDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelAdministrativo.setLayer(lblTextoDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelAdministrativo.setLayer(comBDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelAdministrativoLayout = new javax.swing.GroupLayout(jPanelAdministrativo);
        jPanelAdministrativo.setLayout(jPanelAdministrativoLayout);
        jPanelAdministrativoLayout.setHorizontalGroup(
            jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdministrativoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDepartamento)
                    .addGroup(jPanelAdministrativoLayout.createSequentialGroup()
                        .addGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextoDepartamento)
                            .addComponent(comBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAdministrativoLayout.setVerticalGroup(
            jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdministrativoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comBDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanelAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 250));

        btnGuardar.setText("Guardar Empleado");
        jLayeredPane2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 290, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 10, 12);
        getContentPane().add(jLayeredPane2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comBDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBDepartamentoActionPerformed

    private void btnAñadirAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirAsignaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFIngresarEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAñadirAsignatura;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnGuardarDepartamento;
    public javax.swing.JComboBox<Asignatura> comBAsignatura;
    public javax.swing.JComboBox<Departamento> comBDepartamento;
    public javax.swing.JComboBox<String> comBTipoEmpleado;
    public javax.swing.JComboBox<String> comBTipoProfesor;
    public com.toedter.calendar.JDateChooser jDateIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLayeredPane jPanelAdministrativo;
    public javax.swing.JLayeredPane jPanelAsignatura;
    public javax.swing.JLayeredPane jPanelDepartamento;
    public javax.swing.JLayeredPane jPanelProfesor;
    public javax.swing.JLabel lblAsignatura;
    public javax.swing.JLabel lblEnfoque;
    public javax.swing.JLabel lblEspecialidad;
    public javax.swing.JLabel lblIdDepartamento;
    public javax.swing.JLabel lblNombreDepartamento;
    public javax.swing.JLabel lblTextoDepartamento;
    public javax.swing.JLabel lblTextoProfesor;
    public javax.swing.JLabel lblTipoProfesor;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCargo;
    public javax.swing.JTextField txtEnfoque;
    public javax.swing.JTextField txtEspecialidad;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIdAdministrativo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreDepartamento;
    public javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
