/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author roca
 */
public class JFDialogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFDialogo.class.getName());

    /**
     * Creates new form JFDialogo
     */
    public JFDialogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDialogo = new javax.swing.JTextArea();
        btnSeguir = new javax.swing.JButton();
        lblPersonaje2 = new javax.swing.JLabel();
        lblPersonaje1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dialogos"));

        txtDialogo.setEditable(false);
        txtDialogo.setColumns(20);
        txtDialogo.setLineWrap(true);
        txtDialogo.setRows(5);
        txtDialogo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDialogo);

        jLayeredPane2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 520, 100);

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 540, 130));

        btnSeguir.setText("Seguir");
        getContentPane().add(btnSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));
        getContentPane().add(lblPersonaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 200, 320));
        getContentPane().add(lblPersonaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 200, 320));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 806, 484));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFDialogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSeguir;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblPersonaje1;
    public javax.swing.JLabel lblPersonaje2;
    public javax.swing.JTextArea txtDialogo;
    // End of variables declaration//GEN-END:variables
}
