/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author roca
 */
public class JFVecindad1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFVecindad1.class.getName());

    /**
     * Creates new form JFInicioIngreso
     */
    public JFVecindad1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblFlechaDerecha = new javax.swing.JLabel();
        btnFlechaDerecha = new javax.swing.JButton();
        btnFlechaDerecha.setOpaque(false);          // Quita el fondo opaco
        btnFlechaDerecha.setContentAreaFilled(false); // Quita el relleno de color
        lblFlorinda = new javax.swing.JLabel();
        lblRamon = new javax.swing.JLabel();
        btnFlorindaYRamon = new javax.swing.JButton();
        btnFlorindaYRamon.setOpaque(false);          // Quita el fondo opaco
        btnFlorindaYRamon.setContentAreaFilled(false); // Quita el relleno de color
        lblChilindrina = new javax.swing.JLabel();
        lblQuico = new javax.swing.JLabel();
        btnQuicoYChilindrina = new javax.swing.JButton();
        btnQuicoYChilindrina.setOpaque(false);          // Quita el fondo opaco
        btnQuicoYChilindrina.setContentAreaFilled(false); // Quita el relleno de color
        lblFondoVencidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFlechaDerecha.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaDerecha.png")).getImage().getScaledInstance(130, 60, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblFlechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 130, 60));
        jLayeredPane2.add(btnFlechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 130, 60));

        lblFlorinda.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlorindaEnojada.png")).getImage().getScaledInstance(50, 150, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblFlorinda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 50, 150));

        lblRamon.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RamonEnojado.png")).getImage().getScaledInstance(90, 150, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblRamon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 90, 150));
        jLayeredPane2.add(btnFlorindaYRamon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 240, 170));

        lblChilindrina.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ChilindrinaEnojada.png")).getImage().getScaledInstance(90, 150, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblChilindrina, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 90, 150));

        lblQuico.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/QuicoEnojado.png")).getImage().getScaledInstance(90, 150, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblQuico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 90, 150));
        jLayeredPane2.add(btnQuicoYChilindrina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 240, 170));

        lblFondoVencidad.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vecindad1.jpeg")).getImage().getScaledInstance(830, 460, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblFondoVencidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFVecindad1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnFlechaDerecha;
    public javax.swing.JButton btnFlorindaYRamon;
    public javax.swing.JButton btnQuicoYChilindrina;
    private javax.swing.JLayeredPane jLayeredPane2;
    public javax.swing.JLabel lblChilindrina;
    public javax.swing.JLabel lblFlechaDerecha;
    public javax.swing.JLabel lblFlorinda;
    public javax.swing.JLabel lblFondoVencidad;
    public javax.swing.JLabel lblQuico;
    public javax.swing.JLabel lblRamon;
    // End of variables declaration//GEN-END:variables
}
