/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author roca
 */
public class JFVecindad2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFVecindad2.class.getName());

    /**
     * Creates new form JFInicioIngreso
     */
    public JFVecindad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblFlechaIzquierda = new javax.swing.JLabel();
        btnFlechaDerecha = new javax.swing.JButton();
        btnFlechaDerecha.setOpaque(false);          // Quita el fondo opaco
        btnFlechaDerecha.setContentAreaFilled(false); // Quita el relleno de color
        lblBarriga = new javax.swing.JLabel();
        btnBarriga = new javax.swing.JButton();
        btnBarriga.setOpaque(false);          // Quita el fondo opaco
        btnBarriga.setContentAreaFilled(false); // Quita el relleno de color
        lblPopis = new javax.swing.JLabel();
        btnPopis = new javax.swing.JButton();
        btnPopis.setOpaque(false);          // Quita el fondo opaco
        btnPopis.setContentAreaFilled(false); // Quita el relleno de color
        lblFondoVencidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFlechaIzquierda.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaIzquierda.png")).getImage().getScaledInstance(130, 60, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblFlechaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, 60));
        jLayeredPane2.add(btnFlechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, 60));

        lblBarriga.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Barriga.png")).getImage().getScaledInstance(120, 150, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblBarriga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 120, 150));
        jLayeredPane2.add(btnBarriga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 160, 170));

        lblPopis.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Popis.png")).getImage().getScaledInstance(90, 150, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblPopis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 90, 150));
        jLayeredPane2.add(btnPopis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 130, 170));

        lblFondoVencidad.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vecindad2.jpeg")).getImage().getScaledInstance(830, 460, java.awt.Image.SCALE_SMOOTH)));
        jLayeredPane2.add(lblFondoVencidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFVecindad2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBarriga;
    public javax.swing.JButton btnFlechaDerecha;
    public javax.swing.JButton btnPopis;
    private javax.swing.JLayeredPane jLayeredPane2;
    public javax.swing.JLabel lblBarriga;
    public javax.swing.JLabel lblFlechaIzquierda;
    public javax.swing.JLabel lblFondoVencidad;
    public javax.swing.JLabel lblPopis;
    // End of variables declaration//GEN-END:variables
}
