/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author memoy
 */
public class JFJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFJuego.class.getName());

    /**
     * Creates new form JFJuego
     */
    public JFJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAres = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnEnemigo = new javax.swing.JButton();
        btnAtacarAres = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnInteractuar = new javax.swing.JButton();
        txtVidaWonder = new javax.swing.JTextField();
        txtNivelWonder = new javax.swing.JTextField();
        txtPuntos = new javax.swing.JTextField();
        txtVidaJefe = new javax.swing.JTextField();
        txtCantidadEnemigos = new javax.swing.JTextField();
        txtVidaEnemigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRuletaEquipo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRuletaHabilidad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCuracion = new javax.swing.JButton();
        lblHabilidad = new javax.swing.JLabel();
        btnHabilidad = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Steve.png")).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 100, 100));

        lblAres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAres.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ares.png")).getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH)));
        lblAres.setText("ADES");
        jPanel1.add(lblAres, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 200, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Goomba.png")).getImage().getScaledInstance(130, 200, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 130, 200));

        btnEnemigo.setText("Atacar Enemigo");
        btnEnemigo.addActionListener(this::btnEnemigoActionPerformed);
        jPanel1.add(btnEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        btnAtacarAres.setText("Atacar");
        btnAtacarAres.setToolTipText("");
        btnAtacarAres.addActionListener(this::btnAtacarAresActionPerformed);
        jPanel1.add(btnAtacarAres, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 340, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wonder Woman.png")).getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        jLabel2.setText("wonderWoman");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, 100));

        btnInteractuar.setText("Interactuar");
        jPanel1.add(btnInteractuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        txtVidaWonder.setEditable(false);
        txtVidaWonder.setBorder(javax.swing.BorderFactory.createTitledBorder("Vida"));
        jPanel1.add(txtVidaWonder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, -1));

        txtNivelWonder.setEditable(false);
        txtNivelWonder.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel Base"));
        jPanel1.add(txtNivelWonder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, -1));

        txtPuntos.setEditable(false);
        txtPuntos.setText("0");
        txtPuntos.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntos"));
        jPanel1.add(txtPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        txtVidaJefe.setEditable(false);
        txtVidaJefe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVidaJefe.setBorder(javax.swing.BorderFactory.createTitledBorder("Vida de Jefe"));
        jPanel1.add(txtVidaJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 110, -1));

        txtCantidadEnemigos.setEditable(false);
        txtCantidadEnemigos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadEnemigos.setText("x4");
        jPanel1.add(txtCantidadEnemigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 40, -1));

        txtVidaEnemigo.setEditable(false);
        txtVidaEnemigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Vida"));
        jPanel1.add(txtVidaEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 100, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equipo y Habilidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 12))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ruleta de Equipo: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRuletaEquipo.setText("Requiere 100");
        btnRuletaEquipo.setEnabled(false);
        btnRuletaEquipo.addActionListener(this::btnRuletaEquipoActionPerformed);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ruleta Habilidad:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRuletaHabilidad.setText("Requiere 200");
        btnRuletaHabilidad.setActionCommand("Requiere ");
        btnRuletaHabilidad.setEnabled(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Curación:");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCuracion.setText("Requiere 50");
        btnCuracion.setEnabled(false);
        btnCuracion.addActionListener(this::btnCuracionActionPerformed);

        lblHabilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHabilidad.setText("Habilidad:");
        lblHabilidad.setToolTipText("");
        lblHabilidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHabilidad.setEnabled(false);

        btnHabilidad.setText("...");
        btnHabilidad.setToolTipText("");
        btnHabilidad.setEnabled(false);
        btnHabilidad.addActionListener(this::btnHabilidadActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblHabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRuletaEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRuletaHabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(btnCuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRuletaEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRuletaHabilidad)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 360, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Themyscira.png")).getImage().getScaledInstance(1440, 440, java.awt.Image.SCALE_SMOOTH)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnemigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnemigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnemigoActionPerformed

    private void btnAtacarAresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarAresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtacarAresActionPerformed

    private void btnRuletaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuletaEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRuletaEquipoActionPerformed

    private void btnCuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuracionActionPerformed

    private void btnHabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHabilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtacarAres;
    public javax.swing.JButton btnCuracion;
    public javax.swing.JButton btnEnemigo;
    public javax.swing.JButton btnHabilidad;
    public javax.swing.JButton btnInteractuar;
    public javax.swing.JButton btnRuletaEquipo;
    public javax.swing.JButton btnRuletaHabilidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblAres;
    public javax.swing.JLabel lblHabilidad;
    public javax.swing.JTextField txtCantidadEnemigos;
    public javax.swing.JTextField txtNivelWonder;
    public javax.swing.JTextField txtPuntos;
    public javax.swing.JTextField txtVidaEnemigo;
    public javax.swing.JTextField txtVidaJefe;
    public javax.swing.JTextField txtVidaWonder;
    // End of variables declaration//GEN-END:variables
}
